services:
  - type: web
    name: secure-file-sharing
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
